name: Web based shell container build and push

on:
  push:
    branches:
      - main
    tags:
      - '*'

permissions:
  packages: write

env:
  REGISTRY: ghcr.io
  IMAGE: ${{github.repository}}

jobs:
  build:
    runs-on: ubuntu-24.04
    steps:
      -
        name: Checkout
        uses: actions/checkout@v4
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      -
        name: Docker meta
        id: meta
        uses: docker/metadata-action@v3
        with:
          images: ${{env.REGISTRY}}/${{github.repository}}
          tags: |
            type=ref,event=branch
            type=ref,event=tag
      -
        name: Login to GHCR
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor}} }}
          password: ${{ secrets.GITHUB_TOKEN }}
      -
        name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          platforms: linux/amd64,linux/arm64
          push: ${{ github.event_name != 'pull_request' }}
          tags: |
            ${{ steps.meta.outputs.tags }}
          labels: |
            ${{ steps.meta.outputs.labels }}
          outputs: |
            type=image,name=target,annotation-index.org.opencontainers.image.description=Web based shell
